#!/usr/bin/env python3
# Copyright 2026 Aleksandr Kovalko
# Licensed under the Apache License, Version 2.0
"""Generates the single-header amalgamation of geo-utils-cpp.

Concatenates the library headers in dependency order into one self-contained
file: per-file license banners, `#pragma once`, and local includes are
dropped; system includes are deduplicated and hoisted to the top. The output
is deterministic for a given source tree.

Usage: tools/amalgamate.py [-o geo.hpp]
"""

import argparse
import re
import sys
from pathlib import Path

# Dependency order: each file only relies on the ones before it.
HEADERS = [
    "version.hpp",
    "detail/math.hpp",
    "latlng.hpp",
    "spherical.hpp",
    "poly.hpp",
    "bounds.hpp",
    "encoding.hpp",
]

BANNER = """\
// geo-utils-cpp v{version} — single-header amalgamation (generated, do not edit).
//
// Header-only C++17 library for spherical (lat/lng) geometry on Earth
// coordinates: distance, bearing, polygon area, point-in-polygon,
// snap-to-route, and encoded polylines.
//
//   https://github.com/gistrec/geo-utils-cpp
//
// Generated by tools/amalgamate.py from the headers in include/geo/.
// Equivalent to including <geo/geo.hpp> from the multi-header layout.
//
// Copyright 2026 Aleksandr Kovalko
// Licensed under the Apache License, Version 2.0
//
// Portions of this library are based on Google Maps Android Utils:
// https://github.com/googlemaps/android-maps-utils
//
// Original work:
// Copyright 2013 Google Inc.
// Licensed under the Apache License, Version 2.0
//
// This work has been modified from the original,
// including a port from Java to C++.

#ifndef GEO_UTILS_CPP_SINGLE_HEADER_HPP
#define GEO_UTILS_CPP_SINGLE_HEADER_HPP
#pragma once
"""

FOOTER = "#endif  // GEO_UTILS_CPP_SINGLE_HEADER_HPP\n"


def parse_version(include_dir: Path) -> str:
    text = (include_dir / "version.hpp").read_text()
    parts = {}
    for key in ("MAJOR", "MINOR", "PATCH"):
        m = re.search(rf"#define GEO_UTILS_CPP_VERSION_{key} (\d+)", text)
        if not m:
            sys.exit(f"error: GEO_UTILS_CPP_VERSION_{key} not found in version.hpp")
        parts[key] = m.group(1)
    return "{MAJOR}.{MINOR}.{PATCH}".format(**parts)


def strip_header(path: Path) -> tuple[list[str], list[str]]:
    """Returns (system_includes, body_lines) of one header.

    Drops everything up to and including `#pragma once` (the license banner),
    local `#include "..."` lines, and leading/trailing blank runs.
    """
    lines = path.read_text().splitlines()
    try:
        start = next(i for i, l in enumerate(lines) if l.strip() == "#pragma once") + 1
    except StopIteration:
        sys.exit(f"error: no '#pragma once' in {path}")

    includes, body = [], []
    for line in lines[start:]:
        stripped = line.strip()
        if stripped.startswith('#include "'):
            continue
        if stripped.startswith("#include <"):
            includes.append(stripped)
            continue
        body.append(line)

    while body and not body[0].strip():
        body.pop(0)
    while body and not body[-1].strip():
        body.pop()
    return includes, body


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("-o", "--output", default="geo.hpp", help="output file")
    args = parser.parse_args()

    include_dir = Path(__file__).resolve().parent.parent / "include" / "geo"
    version = parse_version(include_dir)

    all_includes: list[str] = []
    sections: list[str] = []
    for name in HEADERS:
        includes, body = strip_header(include_dir / name)
        all_includes.extend(includes)
        rule = "-" * (66 - len(name))
        sections.append(f"// ---- geo/{name} {rule}\n\n" + "\n".join(body))

    out = [BANNER.format(version=version)]
    out.append("\n".join(sorted(set(all_includes))))
    out.append("\n\n".join(sections))
    out.append(FOOTER)
    Path(args.output).write_text("\n\n".join(out))
    print(f"wrote {args.output} (geo-utils-cpp v{version}, {len(HEADERS)} headers)")


if __name__ == "__main__":
    main()
